Repository SmitBhikadiya-M/NodeJS-Advance-MicroServices, pull requests merged in 2023-05, with the labels that each got.

#1 Setup Boilerplate code of blog microservices project
  blog-boilerplate/client/.gitignore
  blog-boilerplate/client/README.md
  blog-boilerplate/client/package-lock.json
  blog-boilerplate/client/package.json
  blog-boilerplate/client/public/favicon.ico
  blog-boilerplate/client/public/index.html
  blog-boilerplate/client/public/logo192.png
  blog-boilerplate/client/public/logo512.png
  blog-boilerplate/client/public/manifest.json
  blog-boilerplate/client/public/robots.txt
  blog-boilerplate/comments/package.json
  blog-boilerplate/event-bus/package.json
  blog-boilerplate/moderation/package.json
  blog-boilerplate/posts/package.json
  blog-boilerplate/query/package.json
Labels: Intial

#2 Blog project setup initialization
  blog-boilerplate/client/README.md
  blog-boilerplate/client/package-lock.json
  blog-boilerplate/client/src/App.js
  blog-boilerplate/client/src/CommentCreate.js
  blog-boilerplate/client/src/CommentList.js
  blog-boilerplate/client/src/PostCreate.js
  blog-boilerplate/client/src/PostList.js
  blog-boilerplate/client/src/index.js
  blog-boilerplate/comments/.gitignore
  blog-boilerplate/comments/index.js
  blog-boilerplate/comments/package-lock.json
  blog-boilerplate/comments/package.json
  blog-boilerplate/event-bus/package.json
  blog-boilerplate/moderation/package.json
  blog-boilerplate/posts/.gitignore
  blog-boilerplate/posts/index.js
  blog-boilerplate/posts/package-lock.json
  blog-boilerplate/posts/package.json
  blog-boilerplate/query/package.json
Labels: Intial

#4 Added Comment
  blog-boilerplate/ReadME.md
  blog-boilerplate/comments/index.js
  blog-boilerplate/event-bus/index.js
  blog-boilerplate/moderation/index.js
  blog-boilerplate/posts/index.js
  blog-boilerplate/query/index.js
Labels: documentation

#5 Docker Basics
  docker-basic/basic/Dockerfile
  docker-basic/simpleweb/Dockerfile
  docker-basic/simpleweb/index.js
  docker-basic/simpleweb/package.json
Labels: Intial

#6 copied require changes for dockerization phase
  blog-boilerplate/comments/.gitignore
  blog-boilerplate/event-bus/.gitignore
  blog-boilerplate/moderation/.gitignore
  blog-boilerplate/posts/.gitignore
  blog-boilerplate/query/.gitignore
  blog-dockerize/ReadME.md
  blog-dockerize/client/.gitignore
  blog-dockerize/client/README.md
  blog-dockerize/client/package-lock.json
  blog-dockerize/client/package.json
  blog-dockerize/client/public/favicon.ico
  blog-dockerize/client/public/index.html
  blog-dockerize/client/public/logo192.png
  blog-dockerize/client/public/logo512.png
  blog-dockerize/client/public/manifest.json
  blog-dockerize/client/public/robots.txt
  blog-dockerize/client/src/App.js
  blog-dockerize/client/src/CommentCreate.js
  blog-dockerize/client/src/CommentList.js
  blog-dockerize/client/src/PostCreate.js
  blog-dockerize/client/src/PostList.js
  blog-dockerize/client/src/index.js
  blog-dockerize/comments/.gitignore
  blog-dockerize/comments/index.js
  blog-dockerize/comments/package-lock.json
  blog-dockerize/comments/package.json
  blog-dockerize/event-bus/.gitignore
  blog-dockerize/event-bus/index.js
  blog-dockerize/event-bus/package-lock.json
  blog-dockerize/event-bus/package.json
  blog-dockerize/moderation/.gitignore
  blog-dockerize/moderation/index.js
  blog-dockerize/moderation/package-lock.json
  blog-dockerize/moderation/package.json
  blog-dockerize/posts/.gitignore
  blog-dockerize/posts/index.js
  blog-dockerize/posts/package-lock.json
  blog-dockerize/posts/package.json
  blog-dockerize/query/.gitignore
  blog-dockerize/query/index.js
  blog-dockerize/query/package-lock.json
  blog-dockerize/query/package.json
Labels: Intial

#7 Added Dockerfile for all the service of the blog project
  blog-dockerize/comments/.dockerignore
  blog-dockerize/comments/Dockerfile
  blog-dockerize/event-bus/.dockerignore
  blog-dockerize/event-bus/Dockerfile
  blog-dockerize/moderation/.dockerignore
  blog-dockerize/moderation/Dockerfile
  blog-dockerize/posts/.dockerignore
  blog-dockerize/posts/Dockerfile
  blog-dockerize/query/.dockerignore
  blog-dockerize/query/Dockerfile
Labels: Phase completed
